id: AF1A821F1
title: Prayer for the Long Life of His Holiness the Fourteenth Dalai Lama
type: translation
pechas:
- I40AF4ECD
- IF227F048
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:53:28.418687
  last_modified_at: 2023-01-04 11:53:28.418700
  collections:
  - Fourteenth Dalai Lama Series
  - Works of Tibetan Masters
alignment_to_base:
  I40AF4ECD/764F: F3AB
  IF227F048/0CF3: F3AB
